### ISSUE TITLE
Error after adding product using PHP version: 8.1.6

### ISSUE THREAD

**Issue by lemowa** [Eathorne2/simple-php-js-point-of-sale#1]
After adding some product, product list and point of sale didn't display correctly 

this is display error in console point of sale

<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function imagecreatefrompng() in C:\xamppp\htdocs\simple-php-js-point-of-sale-main\77-103_project_files\app\core\functions.php:98
Stack trace:
#0 C:\xamppp\htdocs\simple-php-js-point-of-sale-main\77-103_project_files\app\controllers\ajax.php(38): crop('uploads/5b7a61a...')
#1 C:\xamppp\htdocs\simple-php-js-point-of-sale-main\77-103_project_files\public\index.php(15): require('C:\\xamppp\\htdoc...')
#2 {main}
  thrown in <b>C:\xamppp\htdocs\simple-php-js-point-of-sale-main\77-103_project_files\app\core\functions.php</b> on line <b>98</b><br />

localhost/:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at handle_result ((index):206:18)
    at XMLHttpRequest.<anonymous> ((index):175:7)

**Comment by lemowa** [comment]
must activate gd extension in php.ini
